

# Spark client configuration

client:
  -
    - "spark.sql.warehouse.dir"
    - "s3a://data/warehouse"
  -
    - "spark.hadoop.fs.s3a.path.style.access"
    - true
  -
    - "spark.hadoop.fs.s3a.impl"
    - "org.apache.hadoop.fs.s3a.S3AFileSystem"
  -
    - "fs.s3a.connection.ssl.enabled"
    - false
  -
    - "spark.hadoop.fs.s3a.aws.credentials.provider"
    - "org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider"
  -
    - "spark.sql.extensions"
    - "io.delta.sql.DeltaSparkSessionExtension"
  -
    - "spark.sql.catalog.spark_catalog"
    - "org.apache.spark.sql.delta.catalog.DeltaCatalog"
